### ISSUE TITLE
How come the results are different between the leaderboard and the original paper?

### ISSUE THREAD

**Issue by zhimin-z** [lupantech/ScienceQA#16]
Thanks for your evaluation dataset. However, I found the evaluation results are different between the leaderboard and the original paper. You do not show their best two results in the leaderboards. You actually show the ablation results instead. Why?
![image](https://github.com/lupantech/ScienceQA/assets/8592144/b64f90ab-45ca-4dc9-842c-fb27cb3c3bd4)
![image](https://github.com/lupantech/ScienceQA/assets/8592144/e58b6a75-b6e7-439a-9b2b-5421913cf383)

Original paper link: https://arxiv.org/pdf/2302.00923v4.pdf

https://github.com/lupantech/ScienceQA/issues/5 @lupantech

**Comment by lupantech** [comment]
Hi, the 'T' in Multimodal-CoT (T) refers to the text-only version of the Multimodal-CoT model. Its results are reported in Table 5 at https://arxiv.org/pdf/2302.00923.pdf.

**Comment by zhimin-z** [comment]
But your leaderboard only includes the worst results rather than the best ones, why? @lupantech 
![image](https://github.com/lupantech/ScienceQA/assets/8592144/fb4967e4-8cd7-496f-bb7f-1693b576ba00)
That does not make sense...

**Comment by lupantech** [comment]
Hi Zhimin,

We included the textual version of Multimodal-CoT (# 16) for reasonable comparison with other text-only alternatives, such as LLaMA-Adapter (T) (# 18).

We did add the full version of Multimodal-CoT (# 17, Avg score: 84.91) to the leaderboard, which is not the worst one, as you stated. We selected the base version for comparison because it is more representative of its prior work.

In this leaderboard, we manually maintain it by merging requests from the community. We are open to more contributions and encourage community members to participate. If you have new results to share, please don't hesitate to contact us.

**Comment by zhimin-z** [comment]
> Hi Zhimin,
> 
> We included the textual version of Multimodal-CoT (# 16) for reasonable comparison with other text-only alternatives, such as LLaMA-Adapter (T) (# 18).
> 
> We did add the full version of Multimodal-CoT (# 17, Avg score: 84.91) to the leaderboard, which is not the worst one, as you stated. We selected the base version for comparison because it is more representative of its prior work.
> 
> In this leaderboard, we manually maintain it by merging requests from the community. We are open to more contributions and encourage community members to participate. If you have new results to share, please don't hesitate to contact us.

Not really, you actually include the ablated two results. Why not include the best two?
![image](https://github.com/lupantech/ScienceQA/assets/8592144/c8e71eee-db1f-43cc-bb32-c4d17949233d)

**Comment by lupantech** [comment]
Hi Zhimin,

Please double-check our leaderboard, as the screenshot is shown below:

<img width="1136" alt="image" src="https://github.com/lupantech/ScienceQA/assets/17663606/569cacb7-7620-48a1-a5b4-b68baecd0a14">

- Model 16 - Multimodal-CoT (T) is the textual-only model as reported in Table 5 at https://arxiv.org/pdf/2302.00923.pdf. The model is included for comparison with other textual models in the leaderboard.

- **Model 17 - Multimodal-CoT is not the ablated one**. Its accuracy is 84.91, as reported in the main results in Table 4.

Please note that the Avg score is reported in the first column in our leaderboard, while the Avg score is reported in the last column in the tables of the original paper.

**Comment by zhimin-z** [comment]
> Hi Zhimin,
> 
> Please double-check our leaderboard, as the screenshot is shown below:
> 
> <img alt="image" width="1136" src="https://private-user-images.githubusercontent.com/17663606/285562032-569cacb7-7620-48a1-a5b4-b68baecd0a14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4ODQwNDksIm5iZiI6MTcwMDg4Mzc0OSwicGF0aCI6Ii8xNzY2MzYwNi8yODU1NjIwMzItNTY5Y2FjYjctNzYyMC00OGExLWE1YjQtYjY4YmFlY2QwYTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDAzNDIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNTc4YWY0ZjUyMDA2ZjA3NGY4MWUxNDU3N2JlOWRmYTgxM2NiZWIyNjA2MWU4MzQyYzI2MzhlNTExNjE0MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DW0TfP2s9uq_Ssc5vNJjX9V95qPN9g9wfL7-MjcHRgQ">
> * Model 16 - Multimodal-CoT (T) is the textual-only model as reported in Table 5 at https://arxiv.org/pdf/2302.00923.pdf. The model is included for comparison with other textual models in the leaderboard.
> * **Model 17 - Multimodal-CoT is not the ablated one**. Its accuracy is 84.91, as reported in the main results in Table 4.
> 
> Please note that the Avg score is reported in the first column in our leaderboard, while the Avg score is reported in the last column in the tables of the original paper.

I know all you said. But still, where are the highlighted metrics (these are the best ones as far as I understand)?
![image](https://github.com/lupantech/ScienceQA/assets/8592144/79d29096-f9fb-435b-b094-b215b8a81cca)

**Comment by lupantech** [comment]
Hi Zhimin,

We would like to highlight your comments and our replies to clarify the situation.

> You do not show their best two results in the leaderboards. You actually show the ablation results instead. Why?

**Not true. We did include Multimodal-CoT_base, which is not an ablation result.**

> But your leaderboard only includes the worst results rather than the best ones, why?

**This is not true, as we clarified before.**

We included the textual version of Multimodal-CoT (# 16) for a reasonable comparison with other text-only alternatives, such as LLaMA-Adapter (T) (# 18).

**We also added the full version of Multimodal-CoT (#17, Avg score: 84.91) to the leaderboard, which is not the worst one.** Actually, this model outperforms all prior work before its release date. 

<img width="1148" alt="image" src="https://github.com/lupantech/ScienceQA/assets/17663606/e7a6e6c5-b741-473a-8867-310066859000">

*If we understood correctly, you were curious why Multimodal-CoT_large was not included.*

We selected the base version for comparison because it is more representative of the model's prior work at the time when Multimodal-CoT was released. Accordingly, we also only reported the base versions for # 10 - UnifiedQA and # 11 - UnifiedQA (CoT).

> But still, where are the highlighted metrics (these are the best ones as far as I understand)?

We acknowledge your request to add the largest version of Multimodal-CoT. It makes sense now, as the recent development of large multimodal models has brought forth models like miniGPT-4, Bard, and GPT-4V. We plan to make major updates, including adding Multimodal-CoT_large to the leaderboard to represent the more recent progress in ScienceQA.
