### ISSUE TITLE
Hugging Face dataset

### ISSUE THREAD

**Issue by datavistics** [lupantech/ScienceQA#3]
Hey, awesome work! I wanted to make this more accessible by putting on the huggingface hub: https://huggingface.co/datasets/derek-thomas/ScienceQA

There were a lot of fields in the description card that I filled in as best as I could. Would you consider reviewing this and after it meets your expectations could you add a link on your github repo?

Thanks,
Derek

**Comment by shbone** [comment]
huggingface-hub==0.12.0

**Comment by lupantech** [comment]
Hello Derek,

I wanted to express my gratitude for your work in adding our ScienceQA dataset to HuggingFace. From my review, it looks good. I have a couple of suggestions for improving the dataset's organization:

Firstly, it would be helpful to update the task tags to include `Multiple Choice` and `Question Answering` as tasks, with `multiple-choice-qa`, `closed-domain-qa`, `open-domain-qa`, and `visual-question-answering` as sub-tasks.

Additionally, it would be best to consistently refer to the dataset as `ScienceQA` rather than `SCIENCEQA`.

Thank you again for your efforts.

Best regards, 
Pan

**Comment by shbone** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by datavistics** [comment]
> Firstly, it would be helpful to update the task tags to include Multiple Choice and Question Answering as tasks, with multiple-choice-qa, closed-domain-qa, open-domain-qa, and visual-question-answering as sub-tasks.

> Additionally, it would be best to consistently refer to the dataset as ScienceQA rather than SCIENCEQA.

Done! Just make sure to click on the `+3` on the right to see the rest of the tasks.

<img width="595" alt="image" src="https://user-images.githubusercontent.com/22736772/221258348-e2120d66-826d-44d7-a9e4-1ca08f23373b.png">

**Comment by datavistics** [comment]
If you are ok with it, could you put a link in the download section of the README (or wherever you like)? If not no worries!

**Comment by lupantech** [comment]
Thanks! I have added the link to the Huggingface Datasets in the README.

BTW, the task tags of `Image Classification` and `multi-class-image-classification` might not be good fits for the ScienceQA dataset.
